// flow-typed signature: 95ade7fa07ccfc036444099dae43acb6
// flow-typed version: <<STUB>>/grim_v^1.2.1/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grim'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'grim' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grim/lib/deprecation' {
  declare module.exports: any;
}

declare module 'grim/lib/grim' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grim/lib/deprecation.js' {
  declare module.exports: $Exports<'grim/lib/deprecation'>;
}
declare module 'grim/lib/grim.js' {
  declare module.exports: $Exports<'grim/lib/grim'>;
}
