// flow-typed signature: b79ea4de812e48cf2594aefa4b0e20c8
// flow-typed version: <<STUB>>/joanna_v0.0.6/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'joanna'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'joanna' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'joanna/src/cli' {
  declare module.exports: any;
}

declare module 'joanna/src/generate' {
  declare module.exports: any;
}

declare module 'joanna/src/index' {
  declare module.exports: any;
}

declare module 'joanna/test/generate-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'joanna/src/cli.js' {
  declare module.exports: $Exports<'joanna/src/cli'>;
}
declare module 'joanna/src/generate.js' {
  declare module.exports: $Exports<'joanna/src/generate'>;
}
declare module 'joanna/src/index.js' {
  declare module.exports: $Exports<'joanna/src/index'>;
}
declare module 'joanna/test/generate-test.js' {
  declare module.exports: $Exports<'joanna/test/generate-test'>;
}
