// flow-typed signature: 07103b4dcfc5007360d5f9b70a60e4fa
// flow-typed version: <<STUB>>/tello_v^1.0.6/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'tello'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'tello' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'tello/lib/digester' {
  declare module.exports: any;
}

declare module 'tello/lib/tello-cli' {
  declare module.exports: any;
}

declare module 'tello/lib/tello' {
  declare module.exports: any;
}

// Filename aliases
declare module 'tello/lib/digester.js' {
  declare module.exports: $Exports<'tello/lib/digester'>;
}
declare module 'tello/lib/tello-cli.js' {
  declare module.exports: $Exports<'tello/lib/tello-cli'>;
}
declare module 'tello/lib/tello.js' {
  declare module.exports: $Exports<'tello/lib/tello'>;
}
