// flow-typed signature: 5b9ab0a498b67f0c99a2b033cd839ea9
// flow-typed version: <<STUB>>/temp_v^0.6.0/flow_v0.34.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'temp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'temp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'temp/examples/grepcount' {
  declare module.exports: any;
}

declare module 'temp/examples/pdfcreator' {
  declare module.exports: any;
}

declare module 'temp/lib/temp' {
  declare module.exports: any;
}

declare module 'temp/test/temp-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'temp/examples/grepcount.js' {
  declare module.exports: $Exports<'temp/examples/grepcount'>;
}
declare module 'temp/examples/pdfcreator.js' {
  declare module.exports: $Exports<'temp/examples/pdfcreator'>;
}
declare module 'temp/lib/temp.js' {
  declare module.exports: $Exports<'temp/lib/temp'>;
}
declare module 'temp/test/temp-test.js' {
  declare module.exports: $Exports<'temp/test/temp-test'>;
}
