#!/usr/bin/env node

'use strict';

const tello = require('tello');
const joanna = require('joanna');
const glob = require('glob');
const fs = require('fs-extra');
const path = require('path');

const files = glob.sync('src/**/*.js');
files.pop(); // TODO: Update joanna to handle event-kit.js

const packageJson = JSON.parse(fs.readFileSync('package.json', 'utf-8'));
const jsMetadata = joanna(files);
const metadata = {
  repository: packageJson.repository.url,
  version: packageJson.version,
  files: jsMetadata.files
};

const api = tello.digest([metadata]);

fs.writeFileSync('./api.json', JSON.stringify(api, null, 2))
